version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/praveentravels
  mongo:
    image: mongo
    ports:
      - "27017:27017"
