apiVersion: v1
kind: Service
metadata:
  name: praveentravels-backend
spec:
  selector:
    app: praveentravels-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
